version: "3"
services: 
  mongo:
    image: mongo:3
    container_name: mongodb-container
    restart: always
    ports:
      - "27018:27017"
    volumes: 
      - ./mongo-data:/data/db       
  api: 
    container_name: api-container
    image: node:14
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    ports: 
      - "5050:5050"
      - "9222:9222"
    volumes: 
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    links:
      - mongo